name: IGSQ-Spigot
version: 0.2.0
softdepend: [LuckPerms]
depend: [ProtocolLib]
author: ThaumicTheory
main: thaumictheory.igsq.spigot.Spigot
description: Custom Plugin Made For The Official IGSQ Server
api-version: 1.17

commands:
  igsq:
   aliases: [sq]
   description: Holds Almost Every igsq command.
  faction:
   aliases: [power,allegiance,group]
   description: Igsq Expert Team Commands
   